// bootstrapui
import "./modules/bootstrapui/bootstrapui.module.js";
import "./modules/bootstrapui/alerts.controller.js";
import "./modules/bootstrapui/bootstrapui.config.js";
import "./modules/bootstrapui/buttons.controller.js";
import "./modules/bootstrapui/carousel.controller.js";
import "./modules/bootstrapui/datepicker.controller.js";
import "./modules/bootstrapui/modals.controller.js";
import "./modules/bootstrapui/pagination.controller.js";
import "./modules/bootstrapui/popover.controller.js";
import "./modules/bootstrapui/progress.controller.js";
import "./modules/bootstrapui/rating.controller.js";
import "./modules/bootstrapui/timepicker.controller.js";
import "./modules/bootstrapui/tooltip.controller.js";
import "./modules/bootstrapui/typeahead.controller.js";
// charts
import "./modules/charts/charts.module.js";
import "./modules/charts/chartist.controller.js";
import "./modules/charts/chartjs.controller.js";
import "./modules/charts/chartjs.directive.js";
import "./modules/charts/classyloader.directive.js";
import "./modules/charts/flot-data.service.js";
import "./modules/charts/flot.controller.js";
import "./modules/charts/flot.directive.js";
import "./modules/charts/morris.controller.js";
import "./modules/charts/morris.directive.js";
import "./modules/charts/piecharts.controller.js";
import "./modules/charts/rickshaw.controller.js";
import "./modules/charts/sparklines.directive.js";
// colors
import "./modules/colors/colors.module.js";
import "./modules/colors/colors.contant.js";
import "./modules/colors/colors.service.js";
// core
import "./modules/core/core.module.js";
import "./modules/core/core.config.js";
import "./modules/core/core.constants.js";
import "./modules/core/core.run.js";
// dashboard
import "./modules/dashboard/dashboard.module.js";
import "./modules/dashboard/dashboard.controller.js";
import "./modules/dashboard/dashboard.v2.controller.js";
import "./modules/dashboard/dashboard.v3.controller.js";
// elements
import "./modules/elements/elements.module.js";
import "./modules/elements/carousel.controller.js";
import "./modules/elements/dialog.controller.js";
import "./modules/elements/infinite-scroll.controller.js";
import "./modules/elements/masonry-deck.controller.js";
import "./modules/elements/navtree.controller.js";
import "./modules/elements/nestable.controller.js";
import "./modules/elements/scroll.directive.js";
import "./modules/elements/sortable.controller.js";
import "./modules/elements/sweetalert.controller.js";
import "./modules/elements/toaster.controller.js";
import "./modules/elements/tour.controller.js";
// extras
import "./modules/extras/extras.module.js";
import "./modules/extras/article.controller.js";
import "./modules/extras/calendar.controller.js";
import "./modules/extras/code-editor-loadtree.service.js";
import "./modules/extras/code-editor.controller.js";
import "./modules/extras/todo.controller.js";
import "./modules/extras/word-cloud.controller.js";
// flatdoc
import "./modules/flatdoc/flatdoc.module.js";
import "./modules/flatdoc/flatdoc.directive.js";
// forms
import "./modules/forms/forms.module.js";
import "./modules/forms/color-picker.controller.js";
import "./modules/forms/filestyle.directive.js";
import "./modules/forms/form-imgcrop.controller.js";
import "./modules/forms/form-validation.controller.js";
import "./modules/forms/form-wizard.directive.js";
import "./modules/forms/form-xeditable.controller.js";
import "./modules/forms/forms.controller.js";
import "./modules/forms/masked.directive.js";
import "./modules/forms/props.filter.js";
import "./modules/forms/tags-input.directive.js";
import "./modules/forms/uiselect.controller.js";
import "./modules/forms/upload.controller.js";
// icons
import "./modules/icons/icons.module.js";
import "./modules/icons/icons-skycons.directive.js";
// lazyload
import "./modules/lazyload/lazyload.module.js";
import "./modules/lazyload/lazyload.config.js";
import "./modules/lazyload/lazyload.constants.js";
// loadingbar
import "./modules/loadingbar/loadingbar.module.js";
import "./modules/loadingbar/loadingbar.config.js";
import "./modules/loadingbar/loadingbar.run.js";
// locale
import "./modules/locale/locale.module.js";
import "./modules/locale/locale.config.js";
import "./modules/locale/locale.controller.js";
// mailbox
import "./modules/mailbox/mailbox.module.js";
import "./modules/mailbox/mailbox.controller.js";
import "./modules/mailbox/mailfolder.controller.js";
import "./modules/mailbox/mails.service.js";
import "./modules/mailbox/mailview.controller.js";
// maps
import "./modules/maps/maps.module.js";
import "./modules/maps/maps-google-modal.controller.js";
import "./modules/maps/maps-google.controller.js";
import "./modules/maps/vector-map.directive.js";
import "./modules/maps/vector-map.service.js";
import "./modules/maps/vector-maps.controller.js";
// navsearch
import "./modules/navsearch/navsearch.module.js";
import "./modules/navsearch/navsearch.directive.js";
import "./modules/navsearch/navsearch.service.js";
// notify
import "./modules/notify/notify.module.js";
import "./modules/notify/notify.controller.js";
import "./modules/notify/notify.directive.js";
import "./modules/notify/notify.service.js";
// pages
import "./modules/pages/pages.module.js";
import "./modules/pages/access-login.controller.js";
import "./modules/pages/access-register.controller.js";
// panels
import "./modules/panels/panels.module.js";
import "./modules/panels/panel-collapse.directive.js";
import "./modules/panels/panel-dismiss.directive.js";
import "./modules/panels/panel-refresh.directive.js";
import "./modules/panels/panel-tools.directive.js";
import "./modules/panels/panels.controller.js";
import "./modules/panels/portlet.controller.js";
// preloader
import "./modules/preloader/preloader.module.js";
import "./modules/preloader/preloader.directive.js";
// routes
import "./modules/routes/routes.module.js";
import "./modules/routes/route-helpers.provider.js";
import "./modules/routes/routes.config.js";
// settings
import "./modules/settings/settings.module.js";
import "./modules/settings/settings.run.js";
// sidebar
import "./modules/sidebar/sidebar.module.js";
import "./modules/sidebar/sidebar.controller.js";
import "./modules/sidebar/sidebar.directive.js";
import "./modules/sidebar/sidebar.service.js";
import "./modules/sidebar/sidebar.userblock.controller.js";
// tables
import "./modules/tables/tables.module.js";
import "./modules/tables/angular-grid.controller.js";
import "./modules/tables/datatable.controller.js";
import "./modules/tables/ngtable-data.service.js";
import "./modules/tables/ngtable.controller.js";
import "./modules/tables/table-xeditable.controller.js";
import "./modules/tables/uigrid.controller.js";
// translate
import "./modules/translate/translate.module.js";
import "./modules/translate/translate.config.js";
import "./modules/translate/translate.run.js";
// utils
import "./modules/utils/utils.module.js";
import "./modules/utils/animate-enabled.directive.js";
import "./modules/utils/browser.service.js";
import "./modules/utils/clear-storage.directive.js";
import "./modules/utils/fullscreen.directive.js";
import "./modules/utils/load-css.directive.js";
import "./modules/utils/now.directive.js";
import "./modules/utils/table-checkall.directive.js";
import "./modules/utils/trigger-resize.directive.js";
import "./modules/utils/utils.service.js";

// custom
import "./custom/custom.module.js";
import "./custom/custom.controller.js";

// App module
import "./modules/app.module.js";
