// colors
import "./modules/colors/colors.module.js";
import "./modules/colors/colors.contant.js";
import "./modules/colors/colors.service.js";
// core
import "./modules/core/core.module.js";
import "./modules/core/core.config.js";
import "./modules/core/core.constants.js";
import "./modules/core/core.run.js";
// lazyload
import "./modules/lazyload/lazyload.module.js";
import "./modules/lazyload/lazyload.config.js";
import "./modules/lazyload/lazyload.constants.js";
// loadingbar
import "./modules/loadingbar/loadingbar.module.js";
import "./modules/loadingbar/loadingbar.config.js";
import "./modules/loadingbar/loadingbar.run.js";
// navsearch
import "./modules/navsearch/navsearch.module.js";
import "./modules/navsearch/navsearch.directive.js";
import "./modules/navsearch/navsearch.service.js";
// preloader
import "./modules/preloader/preloader.module.js";
import "./modules/preloader/preloader.directive.js";
// routes
import "./modules/routes/routes.module.js";
import "./modules/routes/route-helpers.provider.js";
import "./modules/routes/routes.config.js";
// settings
import "./modules/settings/settings.module.js";
import "./modules/settings/settings.run.js";
// sidebar
import "./modules/sidebar/sidebar.module.js";
import "./modules/sidebar/sidebar.controller.js";
import "./modules/sidebar/sidebar.directive.js";
import "./modules/sidebar/sidebar.service.js";
import "./modules/sidebar/sidebar.userblock.controller.js";
// translate
import "./modules/translate/translate.module.js";
import "./modules/translate/translate.config.js";
import "./modules/translate/translate.run.js";
// utils
import "./modules/utils/utils.module.js";
import "./modules/utils/animate-enabled.directive.js";
import "./modules/utils/browser.service.js";
import "./modules/utils/clear-storage.directive.js";
import "./modules/utils/fullscreen.directive.js";
import "./modules/utils/load-css.directive.js";
import "./modules/utils/now.directive.js";
import "./modules/utils/table-checkall.directive.js";
import "./modules/utils/trigger-resize.directive.js";
import "./modules/utils/utils.service.js";

// custom
import "./custom/custom.module.js";
import "./custom/custom.controller.js";

// App module
import "./modules/app.module.js";
